-- Psychology MC Questions Batch 9 (17 questions)
INSERT INTO public.cards (
  id,
  user_id,
  front,
  back,
  options,
  correct_option,
  card_type,
  tags,
  created_at
) VALUES
('70c2d771-01bd-47a0-b57f-ccb741691a14', 'be133e38-65b4-4e2d-97b8-f06b118ec5c5', 'Was ist im Experiment die ''abhängige Variable'' (AV)?', '', jsonb_build_array('Körperkontakt (Trost) ist eine wichtigere Bindungsvariable als die bloße Nahrungsquelle.','Die Identifikation der aufrechterhaltenden Bedingungen eines problematischen Verhaltens.','Die Variable, an der die Wirkung der Veränderung der unabhängigen Variable gemessen wird.','Durch Unzuverlässigkeit, Unkontrollierbarkeit und Volatilität des elterlichen Verhaltens.'), 2, 'mc', ARRAY['sozial'], now()),
('fbcaaa70-a40d-4ca5-a095-81ee89ce2dc8', 'be133e38-65b4-4e2d-97b8-f06b118ec5c5', 'Hans Selye bezeichnete Stress metaphorisch als _____.', '', jsonb_build_array('Würze des Lebens','Etwa ab 8 Jahren.','Die Stabilität.','Die Amygdala.'), 0, 'mc', ARRAY['sozial'], now()),
('15e7a0a6-92e5-4ced-82b6-1cb9e064d72b', 'be133e38-65b4-4e2d-97b8-f06b118ec5c5', 'Der professionelle Umgang mit Menschen in sozialen Notlagen erfordert wissenschaftlich fundierte Methoden wie _____, _____ oder _____.', '', jsonb_build_array('Aufmerksamkeitsstörung, Überaktivität und Impulsivität.','Einzelfallhilfe, Gruppenarbeit oder Gemeinwesenarbeit','Genetische Einflüsse und ein Dopaminmangel im Gehirn.','Es existieren insgesamt 79 verschiedene Hauptdiagnosen.'), 1, 'mc', ARRAY['sozial'], now()),
('bf48fa47-4ee1-426b-8004-d2bb43f85cf7', 'be133e38-65b4-4e2d-97b8-f06b118ec5c5', 'Die Psychologie wird definiert als Wissenschaft vom _____ und _____ der Individuen.', '', jsonb_build_array('Klinische Psychologie','Handeln und Erleben','Mit ca. 1,5 Jahren.','Etwa ab 8 Jahren.'), 1, 'mc', ARRAY['sozial'], now()),
('ae0b60b7-60b7-42bb-96b2-185b2dedecb8', 'be133e38-65b4-4e2d-97b8-f06b118ec5c5', 'Was ist die zentrale Aufgabe der Schulsozialarbeit bei Gewaltphänomenen unter Schülern?', '', jsonb_build_array('Soziale Netzwerke, finanzielle Sicherheit oder ein stabiles Wohnumfeld.','Als langandauerndes affektives Band zu nicht auswechselbaren Personen.','Krisenintervention und Durchführung von Trainings zur Gewaltprävention.','Die Kognitive Verhaltenstherapie (KVT) als begleitende Psychotherapie.'), 2, 'mc', ARRAY['sozial'], now()),
('12335f06-c71e-44d1-aec3-f64935237d87', 'be133e38-65b4-4e2d-97b8-f06b118ec5c5', 'Welches Experiment wird oft herangezogen, um zu klären, warum Menschen bereit sind, andere zu foltern?', '', jsonb_build_array('Das Milgram-Experiment zum Gehorsam gegenüber Autoritäten.','Stimulus, Organismus, Reaktion, Kontingenz und Consequenz.','Angststörungen (47,1\%) oder affektive Störungen (38,3\%).','Selbstwirksamkeit, Fachwissen oder physische Konstitution.'), 0, 'mc', ARRAY['sozial'], now()),
('0035f313-62cc-4e66-8a7f-daeea6290ad1', 'be133e38-65b4-4e2d-97b8-f06b118ec5c5', 'In Weiner''s Modell: Ist ''Fähigkeit'' eine internale oder externale Ursache?', '', jsonb_build_array('Konformität (öffentliche Compliance).','Die operante Verstärkung nach Skinner.','Blut-, Spritzen- und Verletzungsphobie.','Internal (innerhalb der Person liegend).'), 3, 'mc', ARRAY['sozial'], now()),
('224a86dd-31bc-4720-9ffe-7b5dc319f189', 'be133e38-65b4-4e2d-97b8-f06b118ec5c5', 'In Weiner''s Modell: Gilt ''Anstrengung'' als stabile oder variable Ursache?', '', jsonb_build_array('Auf das Vorliegen von Suizidgedanken oder akuter Suizidalität.','Eine erhöhte Theta-Aktivität im Vergleich zur Beta-Aktivität.','Anorexia nervosa, Bulimia nervosa und Binge-Eating-Störung.','Variabel (da sie von Situation zu Situation schwanken kann).'), 3, 'mc', ARRAY['sozial'], now()),
('7608d719-1d63-41fe-ad57-6da4fe6ee920', 'be133e38-65b4-4e2d-97b8-f06b118ec5c5', 'Welcher Prozess findet statt, wenn eine Mehrheit ihre Meinung ändert, um nicht aufzufallen?', '', jsonb_build_array('Die operante Verstärkung nach Skinner.','Konformität (öffentliche Compliance).','Internal (innerhalb der Person liegend).','Blut-, Spritzen- und Verletzungsphobie.'), 1, 'mc', ARRAY['sozial'], now()),
('36af699d-e117-4988-93b0-735dab6744be', 'be133e38-65b4-4e2d-97b8-f06b118ec5c5', 'Wie nennt man die psychologische Lehre, die sich mit der ''Gesunderhaltung'' befasst?', '', jsonb_build_array('Salutogenese','Die Amygdala.','WhatsApp.','Die Stabilität.'), 0, 'mc', ARRAY['sozial'], now()),
('1e569d16-d4ba-496c-b009-59abe2ec7cf9', 'be133e38-65b4-4e2d-97b8-f06b118ec5c5', 'Welche Disziplin der Psychologie befasst sich spezifisch mit dem ''Leben mit psychischen Störungen''?', '', jsonb_build_array('Mindestens 6 Symptome.','Klinische Psychologie','Bindung und Sicherheit.','Mit ca. 1,5 Jahren.'), 1, 'mc', ARRAY['sozial'], now()),
('c3b78f49-7557-4835-8521-a73fc8e225c5', 'be133e38-65b4-4e2d-97b8-f06b118ec5c5', 'Ebene sozialer Systeme: Welches System steht über der Organisation?', '', jsonb_build_array('Die Gesellschaft (Makro-Ebene).','Soziale Phobie und Depression.','Die anaklitische Depression.','Selbstvertrauen und Orientierung.'), 0, 'mc', ARRAY['sozial'], now()),
('53d1ec37-ef3a-4757-9b33-1e6ea4576cc3', 'be133e38-65b4-4e2d-97b8-f06b118ec5c5', 'Was ist ein ''Wahrnehmungsfilter''?', '', jsonb_build_array('Sie dient der ersten Stabilisierung, Vermittlung von Hoffnung und Unterstützung bei der sozialen Neuorientierung.','Probleme der Affektregulation, ein negatives Selbstbild (Wertlosigkeit) und dauerhafte Beziehungsschwierigkeiten.','Wiederholte Klagen über körperliche Symptome ohne ausreichenden organischen Befund trotz medizinischer Abklärung.','Ein kognitiver Mechanismus, der bestimmt, welche Umweltreize ins Bewusstsein dringen und welche ignoriert werden.'), 3, 'mc', ARRAY['sozial'], now()),
('de9cf633-68e0-4a37-a864-a68f6222bb37', 'be133e38-65b4-4e2d-97b8-f06b118ec5c5', 'Was beschreibt die ''Reaktionsphase'' in einer Veränderungskrise?', '', jsonb_build_array('Dass die Anwesenheit anderer die Leistung bei einfachen oder gut gelernten Aufgaben verbessert.','Die Phase, in der Gefühle wie Angst, Wut oder Trauer nach dem ersten Schock verarbeitet werden.','Exposition an körpereigenen Signalen (interozeptive Exposition) und kognitive Umstrukturierung.','Weil sie ohne kortikale Beteiligung direkt im emotionalen Erfahrungsgedächtnis abgelegt werden.'), 1, 'mc', ARRAY['sozial'], now()),
('510ab310-81e0-47d0-a14b-9ca928d72c04', 'be133e38-65b4-4e2d-97b8-f06b118ec5c5', 'Warum ist das Milgram-Experiment heute ethisch umstritten?', '', jsonb_build_array('Bei erheblichem Untergewicht, rapidem Gewichtsverlust oder lebensbedrohlichen somatischen Komplikationen.','Depressive Stimmung, Interessen- oder Freudlosigkeit sowie verminderter Antrieb/gesteigerte Ermüdbarkeit.','Die gezielte Nutzung vorhandener Stärken, Fähigkeiten und Potenziale des Klienten zur Problembewältigung.','Wegen der extremen psychischen Belastung der Versuchspersonen, die glaubten, anderen Schmerzen zuzufügen.'), 3, 'mc', ARRAY['sozial'], now()),
('fc0b2641-25af-445e-ab08-c057fb357c57', 'be133e38-65b4-4e2d-97b8-f06b118ec5c5', 'Nenne ein Beispiel für psychosoziale Probleme, die Gegenstand der Sozialen Arbeit sind.', '', jsonb_build_array('Willkürliches Schlussfolgern (Pessimismus ohne Beleg) und Übergeneralisierung.','Soziale Netzwerke, finanzielle Sicherheit oder ein stabiles Wohnumfeld.','Physiologische Ebene, Verhaltensebene, kognitive Ebene und emotionale Ebene.','Familienkonflikte, Isolation, Armut, Gewalt oder Verhaltensauffälligkeiten.'), 3, 'mc', ARRAY['sozial'], now()),
('ccd90347-7a0a-4914-a94e-de9e09d585e8', 'be133e38-65b4-4e2d-97b8-f06b118ec5c5', 'Welche Ursachendimension beschreibt, ob eine Ursache zeitlich von Dauer ist?', '', jsonb_build_array('Etwa ab 8 Jahren.','Die Amygdala.','Würze des Lebens','Die Stabilität.'), 3, 'mc', ARRAY['sozial'], now());